Added all source files
Had issue running the tests Details:

    C:\Tech returners\frontend\React\swapi-app\node_modules\axios\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import axios from './lib/axios.js';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      2 | import './App.css';
      3 | import React, { useEffect, useState } from 'react';
    > 4 | import axios from 'axios';
        | ^
      5 |
      6 |
      7 | const App : React.FC = () => {